service:
  rule_admin_address: localhost:8444
  swagger_address: :8445
  swagger_host: localhost:8445
  rule_diller_address: localhost:8446
  connection_timeout: 10s

postgres:
  dsn: postgres://rule-admin-user:rule-admin-password@localhost:5432/rule-admin-db

kafka:
  brokers: [localhost:9093]
  topic: rule_admin_event
