service:
  rule_admin_address: rule-admin:8444
  swagger_address: :8445
  swagger_host: localhost:8445
  rule_diller_address: rule-diller:8446
  connection_timeout: 10s

postgres:
  dsn: postgres://rule-admin-user:rule-admin-password@rule-admin-db:5432/rule-admin-db

kafka:
  brokers: [kafka:9092]
  topic: rule_admin_event
