version: '3'

services:
  rule_admin:
    hostname: rule-admin
    build:
      context: ../.
      dockerfile: ./infra/rule_admin.Dockerfile
    ports:
      - "8444:8444"
      - "8445:8445"
    depends_on:
      rule_admin_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8444/health"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - kafka-net
      - psql-net

  bandit_indexer:
    hostname: bandit-indexer
    build:
      context: ../.
      dockerfile: ./infra/bandit_indexer.Dockerfile
    ports:
      - "8448:8448"
      - "8449:8449"
    depends_on:
      bandit_indexer_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8448/health"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - kafka-net
      - psql-net

  rule_diller:
    hostname: rule-diller
    build:
      context: ../.
      dockerfile: ./infra/rule_diller.Dockerfile
    ports:
      - "8446:8446"
      - "8447:8447"
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8446/health"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - kafka-net
      - redis-net

  rule_admin_db:
    image: postgres:13
    hostname: rule-admin-db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: rule-admin-db
      POSTGRES_USER: rule-admin-user
      POSTGRES_PASSWORD: rule-admin-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rule-admin-user -d rule-admin-db"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - psql-net

  bandit_indexer_db:
    image: postgres:13
    hostname: bandit-indexer-db
    ports:
    - "5433:5432"
    environment:
      POSTGRES_DB: bandit-indexer-db
      POSTGRES_USER: bandit-indexer-user
      POSTGRES_PASSWORD: bandit-indexer-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bandit-indexer-user -d bandit-indexer-db"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - psql-net

  rule_analytic_db:
    image: postgres:13
    hostname: rule-analytic-db
    ports:
    - "5434:5432"
    environment:
      POSTGRES_DB: rule-analytic-db
      POSTGRES_USER: rule-analytic-user
      POSTGRES_PASSWORD: rule-analytic-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rule-analytic-user -d rule-analytic-db"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - psql-net

  zookeeper:
    image: zookeeper:3.8
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: "server.1=zookeeper:2888:3888;2181"
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "zkServer.sh status"]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka:
    image: bitnami/kafka:3.6
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_NUM_PARTITIONS: "3"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "1"
      KAFKA_CREATE_TOPICS: "internal_rule_analytic:1:1,external_rule_analytic:1:1,bandit_indexer_event:1:1,rule_admin_event:1:1"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 20s
      retries: 15
      start_period: 40s
    networks:
      - kafka-net

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis-net
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  kafka-net:
    driver: bridge
  redis-net:
    driver: bridge
  psql-net:
    driver: bridge
