version: '3'

services:
  
  rule_admin_db:
    image: postgres:10
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: rule-admin
      POSTGRES_USER: rule-admin-user
      POSTGRES_PASSWORD: rule-admin-password

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "example-topic:2:1"
    depends_on:
      - zookeeper
    container_name: example-kafka
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: example-zookeeper

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
    ports:
      - '6379:6379'
