postgres:
  dsn: postgres://rule-analytic-user:rule-analytic-password@rule-analytic-db:5432/rule-analytic-db

clickhouse:
  dsn: clickhouse://rule_analytic_user:rule-analytic-password@clickhouse-db:9000/rule_analytic_db

kafka:
  brokers: [kafka:9092]
  external_topic: external_rule_analytic
  internal_topic: internal_rule_analytic
