postgres:
  dsn: postgres://rule-analytic-user:rule-analytic-password@localhost:5432/rule-analytic-db

clickhouse:
  host: 0.0.0.1
  port: 6432
  user: rule-analytic-user
  dbname: rule-analytic

kafka:
  brokers: [localhost:9093]
  external_topic: external_rule_analytic
  internal_topic: internal_rule_analytic
