test:
  mode: work
  parallel_count: 100
  cycle_count: 10000

service:
  rule_diller_adress: localhost:8446
  rule_admin_address: localhost:8444
  connection_timeout: 10s

kafka:
  brokers: [localhost:9093]
  topic: external_rule_analytic
