service:
  rule_test_address: rule-test:8441
  swagger_address: :8442
  swagger_host: localhost:8442
  rule_diller_address: rule-diller:8446
  rule_admin_address: rule-admin:8444
  connection_timeout: 10s

kafka:
  brokers: [kafka:9092]
  topic: external_rule_analytic

prometheus:
  host: :8443