test:
  mode: work
  parallel_count: 100
  cycle_count: 10000

service:
  rule_diller_adress: rule-diller:8446
  rule_admin_address: rule-admin:8444
  connection_timeout: 10s

kafka:
  brokers: [kafka:9092]
  topic: external_rule_analytic
