service:
  rule_diller_address: localhost:8446
  swagger_address: :8445
  swagger_host: localhost:8447
  bandit_indexer_address: localhost:8448
  rule_admin_address: localhost:8444
  connection_timeout: 10s

redis:
  dsn: redis://localhost:6379/0

kafka:
  brokers: [localhost:9093]
  topic: bandit_indexer_event
