service:
  rule_diller_address: 0.0.0.0:8444
  swagger_address: 0.0.0.0:8445
  swagger_host: rule.admin.swagger.bandit.ebumba.ru
  bandit_indexer_address: rule-diller:8443
  rule_admin_address: rule-admin:8443
  connection_timeout: 10s

redis:
  host: 0.0.0.1
  port: 6432
  user: rule-admin-user
  dbname: rule-admin

kafka:
  brokers: broker1, broker2
  topic: bandit_indexer_event
