// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.3
// source: bandit-indexer/api/indexer.proto

package banditindexer

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRuleScoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRuleScoresRequest) Reset() {
	*x = GetRuleScoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bandit_indexer_api_indexer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRuleScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleScoresRequest) ProtoMessage() {}

func (x *GetRuleScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bandit_indexer_api_indexer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleScoresRequest.ProtoReflect.Descriptor instead.
func (*GetRuleScoresRequest) Descriptor() ([]byte, []int) {
	return file_bandit_indexer_api_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *GetRuleScoresRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRuleScoresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  uint64     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Variants []*Variant `protobuf:"bytes,2,rep,name=variants,proto3" json:"variants,omitempty"`
}

func (x *GetRuleScoresResponse) Reset() {
	*x = GetRuleScoresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bandit_indexer_api_indexer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRuleScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleScoresResponse) ProtoMessage() {}

func (x *GetRuleScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bandit_indexer_api_indexer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleScoresResponse.ProtoReflect.Descriptor instead.
func (*GetRuleScoresResponse) Descriptor() ([]byte, []int) {
	return file_bandit_indexer_api_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *GetRuleScoresResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetRuleScoresResponse) GetVariants() []*Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type Variant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score float64 `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Count uint64  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *Variant) Reset() {
	*x = Variant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bandit_indexer_api_indexer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_bandit_indexer_api_indexer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_bandit_indexer_api_indexer_proto_rawDescGZIP(), []int{2}
}

func (x *Variant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Variant) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Variant) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_bandit_indexer_api_indexer_proto protoreflect.FileDescriptor

var file_bandit_indexer_api_indexer_proto_rawDesc = []byte{
	0x0a, 0x20, 0x62, 0x61, 0x6e, 0x64, 0x69, 0x74, 0x2d, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1d, 0x62, 0x61, 0x6e, 0x64, 0x69, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x62, 0x61, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65,
	0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x75, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52,
	0x75, 0x6c, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x08, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x62, 0x61, 0x6e, 0x64, 0x69, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x62, 0x61, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x22,
	0x45, 0x0a, 0x07, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xb2, 0x01, 0x0a, 0x14, 0x42, 0x61, 0x6e, 0x64, 0x69,
	0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x99, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x12, 0x33, 0x2e, 0x62, 0x61, 0x6e, 0x64, 0x69, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x62, 0x61, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x62, 0x61, 0x6e, 0x64, 0x69, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x61, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65,
	0x72, 0x2f, 0x72, 0x75, 0x6c, 0x65, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x11, 0x5a, 0x0f, 0x2e,
	0x2f, 0x62, 0x61, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bandit_indexer_api_indexer_proto_rawDescOnce sync.Once
	file_bandit_indexer_api_indexer_proto_rawDescData = file_bandit_indexer_api_indexer_proto_rawDesc
)

func file_bandit_indexer_api_indexer_proto_rawDescGZIP() []byte {
	file_bandit_indexer_api_indexer_proto_rawDescOnce.Do(func() {
		file_bandit_indexer_api_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(file_bandit_indexer_api_indexer_proto_rawDescData)
	})
	return file_bandit_indexer_api_indexer_proto_rawDescData
}

var file_bandit_indexer_api_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bandit_indexer_api_indexer_proto_goTypes = []interface{}{
	(*GetRuleScoresRequest)(nil),  // 0: bandit.services.banditindexer.GetRuleScoresRequest
	(*GetRuleScoresResponse)(nil), // 1: bandit.services.banditindexer.GetRuleScoresResponse
	(*Variant)(nil),               // 2: bandit.services.banditindexer.Variant
}
var file_bandit_indexer_api_indexer_proto_depIdxs = []int32{
	2, // 0: bandit.services.banditindexer.GetRuleScoresResponse.variants:type_name -> bandit.services.banditindexer.Variant
	0, // 1: bandit.services.banditindexer.BanditIndexerService.GetRuleScores:input_type -> bandit.services.banditindexer.GetRuleScoresRequest
	1, // 2: bandit.services.banditindexer.BanditIndexerService.GetRuleScores:output_type -> bandit.services.banditindexer.GetRuleScoresResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bandit_indexer_api_indexer_proto_init() }
func file_bandit_indexer_api_indexer_proto_init() {
	if File_bandit_indexer_api_indexer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bandit_indexer_api_indexer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRuleScoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bandit_indexer_api_indexer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRuleScoresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bandit_indexer_api_indexer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Variant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bandit_indexer_api_indexer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bandit_indexer_api_indexer_proto_goTypes,
		DependencyIndexes: file_bandit_indexer_api_indexer_proto_depIdxs,
		MessageInfos:      file_bandit_indexer_api_indexer_proto_msgTypes,
	}.Build()
	File_bandit_indexer_api_indexer_proto = out.File
	file_bandit_indexer_api_indexer_proto_rawDesc = nil
	file_bandit_indexer_api_indexer_proto_goTypes = nil
	file_bandit_indexer_api_indexer_proto_depIdxs = nil
}
